[package]
name = "zvariant"
version = "2.0.0"
authors = ["Zeeshan Ali <zeeshanak@gnome.org>"]
edition = "2018"

description = "API for D-Bus wire format encoding & decoding"
repository = "https://gitlab.freedesktop.org/zeenix/zbus/"
documentation = "http://docs.rs/zvariant/"
keywords = ["D-Bus", "DBus", "IPC"]
license = "MIT"
categories = ["data-structures", "encoding", "parsing"]
readme = "../README.md"

[dependencies]
byteorder = "1.3.1"
serde = "1.0"
serde_derive = "1.0"

[dependencies.flagset]
git = "https://github.com/zeenix/flagset.git"
branch = "serde"
features = [ "serde" ]
optional = true

[dev-dependencies]
zvariant_derive = { path = "../zvariant_derive", version = "^2" }
serde_json = "1.0"
serde_repr = "0.1"
